
import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "../styles/globals.css";
import { SolanaProvider } from "@/components/providers/wallet-adapter";

const geistSans = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solfund",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased`}
      >
        <SolanaProvider>
          {children}

        </SolanaProvider>
      </body>
    </html>
  );
}
